version: '3'

services:
  petwin:
    build:
      context: .
      dockerfile: Dockerfile
    image: petwin
    container_name: petwin
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGODB_CONN=$MONGODB_CONN
      - MONGODB_NAME=$MONGODB_NAME
      - SECRETORPUBLICKEY=$SECRETORPUBLICKEY
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_SECRET_ID=$GOOGLE_SECRET_ID
    ports:
      - "4000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

  # db:
  #   image: mongo:4.1.8-xenial
  #   container_name: db
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:     
  #     - dbdata:/data/db
  #   networks:
  #     - app-network  

networks:
  default:
    external: true
    name: nginx-network

volumes:
  node_modules: